# 采购订单原型验收测试：对打包后的 Vue 原型（dist/index.html）逐条点主PRD 验收标准
# 先执行 npm run build，再运行：/tmp/pwenv/bin/python 原型验收测试.py
# 每次运行前先点"重置演示数据"，保证从 12 张初始订单开始
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from playwright.sync_api import sync_playwright
from 公共 import 页面, URL, CHROME

res = []; errs = []
def ok(n, c, msg=''):
    res.append((n, bool(c), msg)); print('PASS' if c else 'FAIL', n, '' if c else msg)

with sync_playwright() as p:
    b = p.chromium.launch(executable_path=CHROME, args=['--no-sandbox'])
    pg = b.new_page(viewport={'width': 1440, 'height': 900})
    pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.on('console', lambda m: errs.append(m.text[:200]) if m.type == 'error' else None)
    P = 页面(pg)
    pg.goto(URL); P.等(1200)
    P.重置演示数据()
    行 = lambda: pg.locator('[data-anno=L4] .el-table__body tbody tr').count()

    ok('列表打开', 行() == 10, str(行()))
    ok('分页2页', pg.locator('.el-pager li').count() == 2)
    P.身份('老板'); ok('1 老板无新建', pg.locator('#btnNew').count() == 0)
    P.身份('采购员'); ok('采购员有新建', pg.locator('#btnNew').count() == 1)
    pg.click('#btnNew'); P.等()
    opts = P.下拉选项('.el-select:has(#fSid)')
    ok('2 停用供应商不出现', opts and not any('旧友' in o for o in opts), str(opts))
    pg.click('#addLine'); P.等(200)
    popts = P.下拉选项('.lpid >> nth=0')
    ok('3a 停用商品不出现', popts and not any('苏打' in o for o in popts), str(popts))
    pg.click('#fSubmit'); P.等(200)
    ok('必填校验', '请选择供应商' in P.文字() and '请选择商品' in P.文字())
    P.选('.el-select:has(#fSid)', '杭州优果')
    P.选('.lpid >> nth=0', '原味薯片')
    ok('4 带出上次进价', pg.input_value('.lprice input >> nth=0') == '84.00', pg.input_value('.lprice input >> nth=0'))
    pg.click('#addLine'); P.等(200)
    popts = P.下拉选项('.lpid >> nth=1')
    ok('3b 已选商品不出现', '原味薯片' not in popts, str(popts))
    P.选('.lpid >> nth=1', '矿泉水')
    ok('5 无上次进价带参考进价', pg.input_value('.lprice input >> nth=1') == '18.00')
    P.填('.lqty input >> nth=0', '100')
    P.填('.lqty input >> nth=1', '0')
    ok('数量校验', '请输入大于 0 的整数' in P.文字())
    P.填('.lqty input >> nth=1', '10')
    P.填('.lprice input >> nth=0', '90')
    ok('6a 涨价标记', pg.locator('[data-anno=F3] .rise').count() == 1)
    t = P.文字('[data-anno=F5]')
    ok('金额与层级', '9,180.00' in t and '采购组长' in t, t)
    P.填日期('#fEta', '2020-01-01')
    pg.click('#fSubmit'); P.等(200)
    ok('7 日期先后', '期望到货日期不能早于下单日期' in P.文字())
    P.填日期('#fEta', '2099-01-01')
    pg.click('#fSubmit'); P.等(300)
    ok('6b 涨价提醒弹窗', '涨价提醒' in P.确认框文字())
    P.确认(); P.等(500)
    ok('提交成功进详情', '#/purchase/cgdd/CGDD-' in pg.url and '待审核' in P.文字('.head'), pg.url)
    ok('采购员看待审核无审核按钮且有撤回', '撤回' in P.按钮() and '审核通过' not in P.按钮(), str(P.按钮()))

    # 9/10 金额边界：20000 与 20000.01
    def mk(qty, price):
        P.去('/purchase/cgdd')
        if P.有确认框(): P.确认()
        P.去('/purchase/cgdd/new')
        P.选('.el-select:has(#fSid)', '浙江清泉'); pg.click('#addLine'); P.等(150)
        P.选('.lpid >> nth=0', '原味薯片')
        P.填('.lprice input >> nth=0', price)
        P.填('.lqty input >> nth=0', qty)
        return P.文字('[data-anno=F5]')
    ok('9 20000 组长', '采购组长' in mk('1', '20000.00'))
    ok('10 20000.01 老板', '老板' in mk('1', '20000.01'))
    P.去('/purchase/cgdd')
    ok('路由离开拦截', P.有确认框()); P.确认()
    P.去('/purchase/cgdd/new'); P.选('.el-select:has(#fSid)', '浙江清泉')
    pg.click('#fCancel'); P.等(300)
    ok('离开确认', '有未保存的修改' in P.确认框文字()); P.确认()

    # 11 组长自建 → 老板
    P.身份('采购组长'); P.去('/purchase/cgdd/CGDD-20261013-0002')
    d2 = P.文字('[data-anno=D2]')
    ok('11 组长自建单层级老板且无审核', '老板' in d2 and '审核通过' not in P.按钮() and '本单由【老板】审核' in d2, str(P.按钮()))
    P.去('/purchase/cgdd/CGDD-20261013-0001')
    ok('12 组长看老板层级单无审核', '审核通过' not in P.按钮())
    P.去('/purchase/cgdd/CGDD-20261012-0002')
    ok('组长可审组长层级单', '审核通过' in P.按钮() and '驳回' in P.按钮())
    P.点按钮('驳回'); pg.click('#mOk'); P.等(200)
    ok('13 驳回原因必填', '请填写原因' in P.文字('.reason-body'))
    pg.fill('#reason', '数量再核一下'); pg.click('#mOk'); P.等(600)
    ok('14a 驳回回草稿', '草稿' in P.文字('.head'))
    P.身份('采购员'); P.去('/purchase/cgdd/CGDD-20261012-0002/edit')
    ok('14b 编辑页显示驳回原因', pg.locator('[data-anno=F1]').count() and '数量再核一下' in P.文字('[data-anno=F1]'))
    P.身份('老板'); P.去('/purchase/cgdd/CGDD-20261013-0001')
    ok('老板可审老板层级', '审核通过' in P.按钮())
    ok('审核页涨价标记', pg.locator('[data-anno=D3] .rise').count() == 1)
    P.点按钮('审核通过'); P.确认()
    ok('15 审核通过生成入库单', '已审核' in P.文字('.head') and '待执行' in P.文字('[data-anno=D4]'))
    P.身份('采购员'); P.去('/purchase/cgdd/CGDD-20261013-0001')
    ok('创建人可作废', '作废' in P.按钮())
    P.点按钮('作废'); pg.fill('#reason', '测试作废'); pg.click('#mOk'); P.等(600)
    ok('16 作废后入库单取消', '已作废' in P.文字('.head') and '已取消' in P.文字('[data-anno=D4]'))
    P.去('/purchase/cgdd/CGDD-20261008-0001')
    ok('17a 部分完成无作废有关闭', '作废' not in P.按钮() and '关闭' in P.按钮(), str(P.按钮()))
    P.点按钮('关闭'); pg.fill('#reason', '剩余不送'); pg.click('#mOk'); P.等(600)
    ok('17b 关闭后入库单取消', '已关闭' in P.文字('.head') and '待执行' not in P.文字('[data-anno=D4]'))
    for no in ['CGDD-20261005-0001', 'CGDD-20261003-0001', 'CGDD-20261002-0001']:
        P.去('/purchase/cgdd/' + no); ok('18 终态只有返回 ' + no, P.按钮() == ['返回列表'], str(P.按钮()))
    P.去('/purchase/cgdd/CGDD-20261013-0003')
    ok('19 非创建人草稿无编辑', P.按钮() == ['返回列表'], str(P.按钮()))
    P.身份('老板'); P.去('/purchase/cgdd/CGDD-20261010-0001')
    ok('老板不能作废已审核', '作废' not in P.按钮())
    P.身份('采购组长'); P.去('/purchase/cgdd/CGDD-20261010-0001')
    ok('组长可作废他人已审核', '作废' in P.按钮())

    # 角标
    pg.locator('.el-switch:has(#annoSw)').click(); P.等(200)
    found = set()
    P.身份('采购员')
    for h in ['/purchase/cgdd', '/purchase/cgdd/new', '/purchase/cgdd/CGDD-20261011-0001/edit', '/purchase/cgdd/CGDD-20261012-0002']:
        P.去(h)
        if P.有确认框(): P.确认()
        found |= set(pg.locator('[data-anno]').evaluate_all('els=>els.map(e=>e.dataset.anno)'))
    P.身份('老板'); P.去('/purchase/cgdd/CGDD-20261013-0002')
    P.点按钮('驳回')
    found |= set(pg.locator('[data-anno]').evaluate_all('els=>els.map(e=>e.dataset.anno)'))
    badges = pg.locator('.anno-badge:visible').count()
    need = {f'L{i}' for i in range(1, 7)} | {f'F{i}' for i in range(1, 8)} | {f'D{i}' for i in range(1, 8)}
    ok('角标齐全', need <= found and badges > 0, str(sorted(need - found)))
    pg.click('#mCancel'); P.等(200)

    # 新增：本地数据库——刷新后数据还在；重置后恢复初始
    pg.reload(); P.等(1200)
    P.去('/purchase/cgdd/CGDD-20261008-0001')
    ok('刷新后数据还在（本地数据库）', '已关闭' in P.文字('.head'))
    P.重置演示数据()
    P.去('/purchase/cgdd/CGDD-20261008-0001')
    ok('重置演示数据后恢复初始', '部分完成' in P.文字('.head'))
    ok('无JS报错', not errs, str(errs[:3]))
    b.close()
print('TOTAL', sum(1 for r in res if r[1]), '/', len(res))
